Repository unimelb/pattern-lib, pull requests merged in 2019-11, with the labels that each got.

#1336 fix(media gallery) fix z-index so it overlays footer
  components/media-gallery/_media-gallery.css
Labels: pr-patch

#1182 feat(component): screen reader jump to
  components/_utils.css
  components/index.css
  components/screen-reader-jump-to/ScreenReaderJumpTo.vue
  components/screen-reader-jump-to/__tests__/ScreenReaderJumpTo.test.js
  components/screen-reader-jump-to/__tests__/__snapshots__/ScreenReaderJumpTo.test.js.snap
  components/screen-reader-jump-to/index.css
  components/screen-reader-jump-to/stories/Default.vue
  components/screen-reader-jump-to/stories/index.js
  components/screen-reader-jump-to/stories/screenReaderMd.md
  targets/lib/index.js
  targets/vue/index.js
  yarn.lock
Labels: pr-minor

#1342 chore(component): page footer add accomodation link and fix phone number
  components/footer/PageFooterSitemap.vue
  components/footer/PageFooterUpper.vue
Labels: pr-patch

#1331 fix(component): card features panel title
  components/cards/_card-features-panel.css
Labels: pr-patch

#1344 chore(component): footer update strategy link
  components/footer/PageFooterSitemap.vue
Labels: Review Wanted

#1345 chore(upgrade) update stylelint packages
  components/article-wrap/index.css
  components/content-block/index.css
  package.json
  yarn.lock
Labels: pr-patch

#1343 chore(upgrade) updated to eslint 6
  .nvmrc
  .storybook/config.js
  .storybook/utils/__tests__/create-story.test.js
  .storybook/utils/create-story.js
  .storybook/utils/story-decorator.js
  .storybook/webpack.config.js
  components/article-wrap/ArticleWrap.vue
  components/breadcrumbs/PageBreadcrumbs.vue
  components/buttons/ButtonIcon.vue
  components/cards/CardFocusBox.vue
  components/cards/CardLink.vue
  components/cards/CardNewsTag.vue
  components/cards/CardStat.vue
  components/cards/GenericCard.vue
  components/carousel/Carousel.vue
  components/check-list/CheckList.vue
  components/content-block/ContentBlock.vue
  components/embed/SoundcloudEmbed.vue
  components/embed/VideoEmbed.vue
  components/focus-wrapper/FocusWrapper.vue
  components/header/PageHeader.vue
  components/logo/Logo.vue
  components/megamenu/MegaMenu.vue
  components/navigation/InPageNavigation.vue
  components/shared/utils/load-script.js
  components/tables/BootstrapCMSTables.js
  package.json
  yarn.lock
Labels: Review Wanted

#1347 fix(ToggleBlock|Modal) fix focusable elements error
  components/modal/ModalDialog.vue
  components/modal/__tests__/ModalDialog.test.js
  components/toggle/ToggleBlock.vue
  utils/focusable-elements.js
Labels: pr-patch

#1351 feature(styled-select) update to new design
  components/filter/__tests__/__snapshots__/AccordionFilter.test.js.snap
  components/filter/__tests__/__snapshots__/CardsFilter.test.js.snap
  components/filter/filters-core/filters/DropdownFilter.vue
  components/forms/StyledSelect.vue
  components/forms/__tests__/__snapshots__/StyledSelect.test.js.snap
  components/forms/_select.css
  components/tabs/Tabs.vue
  components/tabs/index.css
  components/tabs/stories/TabsSelect.vue
  components/tabs/stories/index.js
Labels: pr-minor

#1354 chore(update) update footer with new about us link
  components/footer/PageFooterSitemap.vue
Labels: pr-patch

#1356 chore(update) Update styled-select to not use svgicon
  components/filter/__tests__/__snapshots__/AccordionFilter.test.js.snap
  components/filter/__tests__/__snapshots__/CardsFilter.test.js.snap
  components/forms/StyledSelect.vue
  components/forms/__tests__/__snapshots__/StyledSelect.test.js.snap
  components/forms/_select.css
  package.json
  postcss.config.js
  targets/lib/index.js
  targets/vue/index.js
  yarn.lock
Labels: pr-patch
