Repository unimelb/pattern-lib, pull requests merged in 2019-12, with the labels that each got.

#1360 chore(component) update styled-select - add ability to pass options object
  components/dropdown/stories/DropdownChange.vue
  components/dropdown/stories/index.js
  components/filter/__tests__/__snapshots__/AccordionFilter.test.js.snap
  components/filter/__tests__/__snapshots__/CardsFilter.test.js.snap
  components/forms/StyledSelect.vue
  components/forms/__tests__/__snapshots__/StyledSelect.test.js.snap
  components/forms/_select.css
  components/tabs/Tabs.vue
  components/tabs/index.css
  components/tabs/stories/TabsAltMin.vue
  components/tabs/stories/index.js
  package.json
Labels: pr-patch

#1363 fix(component) fix tabs not working in cms
  components/tabs/Tabs.vue
Labels: pr-patch

#1365 upgrade(component) Add label to styled-select
  components/filter/__tests__/__snapshots__/AccordionFilter.test.js.snap
  components/filter/__tests__/__snapshots__/CardsFilter.test.js.snap
  components/forms/StyledSelect.vue
  components/forms/__tests__/StyledSelect.test.js
  components/forms/__tests__/__snapshots__/StyledSelect.test.js.snap
  components/forms/_select.css
  components/forms/stories/StyledSelect.vue
Labels: pr-patch

#1366 fix(component) fix button hover states
  components/buttons/index.css
Labels: pr-patch

#1369 fix(tabs) fix select for ie 11
  components/tabs/Tabs.vue
Labels: pr-patch

#1368 update(component) implement label for tabs select
  components/forms/_select.css
  components/tabs/Tabs.vue
  components/tabs/index.css
  components/tabs/stories/TabsSelect.vue
  components/tabs/stories/tabsSelect.md
Labels: pr-patch

#1371 feature(component) Update tabs alternative
  components/tabs/Tabs.vue
  components/tabs/__tests__/Tabs.test.js
  components/tabs/__tests__/__snapshots__/Tabs.test.js.snap
  components/tabs/index.css
  components/tabs/stories/TabsAlt.vue
  components/tabs/stories/tabsAlt.md
Labels: pr-minor

#1375 fix(component): selector blue label
  components/forms/_select.css
  components/tabs/index.css
  components/tabs/stories/TabsSelect.vue
Labels: Review Wanted, pr-patch

#1377 chore(component) Tabs - hide select if there is only one tab
  components/tabs/Tabs.vue
  components/tabs/__tests__/__snapshots__/Tabs.test.js.snap
  components/tabs/stories/TabsSelect.vue
  components/tabs/stories/tabsSelect.md
Labels: pr-minor

#1378 fix(component) Tabs - Fix white space above select
  components/tabs/index.css
Labels: pr-patch

#1376 feat(component): responsive tabs
  components/tabs/Tabs.vue
  components/tabs/__tests__/__snapshots__/Tabs.test.js.snap
  components/tabs/index.css
  components/tabs/stories/TabsAlt.vue
  package.json
Labels: pr-minor

#1379 fix(component) fix tabs select not showing default value
  components/tabs/Tabs.vue
Labels: pr-patch

#1383 chore(tabs): update tabs functionality and design
  components/tabs/Tabs.vue
  components/tabs/index.css
Labels: pr-patch

#1385 fix(component): selector dropdown
  components/forms/_select.css
Labels: pr-patch

#1387 fix(component): tabs active
  components/tabs/index.css
Labels: pr-patch
