Repository unimelb/pattern-lib, pull requests merged in 2019-08, with the labels that each got.

#1224 fix(component): mega menu inner colour
  components/megamenu/_mega-menu.css
Labels: pr-patch

#1221 update(component): carousel image position and story
  components/breadcrumbs/index.css
  components/carousel/Carousel.vue
  components/carousel/__tests__/Carousel.test.js
  components/carousel/index.css
  components/carousel/sample.json
  components/carousel/stories/carousel-doc.md
Labels: pr-patch

#1228 fix(component): generic card images height
  components/cards/GenericCard.vue
  components/cards/__tests__/GenericCard.test.js
  components/cards/__tests__/__snapshots__/GenericCard.test.js.snap
  components/cards/_card-generic.css
  components/cards/_card.css
  components/cards/stories/GenericCard/Story6.vue
Labels: pr-patch

#1229 chore(headings): letter spacing lager heading classes
  components/typography/_titles.css
Labels: pr-patch

#1225 refactor(component): social list bar to be reusable
  components/article-wrap/ArticleWrap.vue
  components/footer/PageFooterUpper.vue
  components/social-list/SocialListGeneric.vue
  components/social-list/__tests__/SocialList.test.js
  components/social-list/__tests__/__snapshots__/SocialList.test.js.snap
  components/social-list/stories/SocialListGeneric.vue
  components/social-list/stories/index.js
  components/social-media-bar/SocialMediaBar.vue
  components/social-media-bar/__tests__/__snapshots__/SocialMediaBar.test.js.snap
  components/social-media-bar/index.css
Labels: Review Wanted

#1222 feat(component): event info / sidebar
  components/buttons/index.css
  components/buttons/stories/StoryButtonEvent.vue
  components/buttons/stories/index.js
  components/index.css
  components/sidebar/Sidebar.vue
  components/sidebar/__tests__/Sidebar.test.js
  components/sidebar/__tests__/__snapshots__/Sidebar.test.js.snap
  components/sidebar/index.css
  components/sidebar/sample.json
  components/sidebar/sidebar.md
  components/sidebar/stories/Story1.vue
  components/sidebar/stories/index.js
  targets/lib/index.js
  targets/vue/index.js
Labels: pr-minor

#1226 feat(component): header text with cta and social list
  components/footer/PageFooterUpper.vue
  components/header/PageHeaderEvent.vue
  components/header/__tests__/PageHeaderEvent.test.js
  components/header/__tests__/__snapshots__/PageHeaderEvent.test.js.snap
  components/header/index.css
  components/header/page-header-event.css
  components/header/stories/event/Default.vue
  components/header/stories/event/index.js
  components/header/stories/index.js
  components/social-list/stories/SocialListGeneric.vue
  components/social-media-bar/SocialMediaBar.vue
  targets/lib/index.js
  targets/vue/index.js
Labels: pr-minor

#1236 chore(headings) add letter-spacing to missing classes
  components/accordion/index.css
  components/typography/_headings.css
Labels: pr-patch

#1235 fix(component): carousel image load
  components/carousel/Carousel.vue
  components/carousel/__tests__/Carousel.test.js
Labels: pr-patch

#1239 fix(component): social media bar icons
  components/social-media-bar/SocialMediaBar.vue
Labels: pr-patch

#1238 chore(component): Carousel and Full width image consistent image height
  components/carousel/index.css
  components/figure/_full-width-image.css
Labels: pr-patch

#1237 fix(component): cards subtitle and excerpt
  components/cards/CardNewsTag.vue
  components/cards/_card-events.css
  components/cards/_card-generic.css
  components/cards/_card-news-tag.css
  components/cards/index.css
Labels: pr-patch

#1243 fix(constrast): search and hamburger menu
  components/megamenu/_mega-menu.css
  components/search/_header-tools.css
Labels: pr-patch

#1247 chore(carousel) remove component from pattern-lib-vue
  components/carousel/stories/carousel-doc.md
  targets/vue/index.js
Labels: pr-patch

#1248 fix(minification) force cssnano to not compress keyframe names
  webpack.config.base.js
Labels: pr-patch

#1242 chore(filter): acccordion update data structure
  components/filter/__tests__/AccordionFilter.test.js
  components/filter/__tests__/__snapshots__/AccordionFilter.test.js.snap
  components/filter/__tests__/__snapshots__/CardsFilter.test.js.snap
  components/filter/accordion/AccordionFilter.vue
  components/filter/accordion/accordion.md
  components/filter/accordion/accordionCMS.md
  components/filter/accordion/data.json
  components/filter/cards/CardsFilter.vue
  components/filter/cards/data.json
  components/filter/stories/AccordionFilterStory.vue
  components/filter/stories/AccordionFilterStoryCMS.vue
Labels: pr-patch

#1255 chore(export): social list generic
  targets/lib/index.js
  targets/vue/index.js
Labels: pr-patch

#1240 fix(components): svg icon missing import
  .storybook/config.js
  components/article-wrap/stories/Tags.vue
  components/cards/CardLink.vue
  components/cards/CardPathfinder.vue
  components/cards/CardStaffList.vue
  components/cards/__tests__/__snapshots__/CardLink.test.js.snap
  components/cards/__tests__/__snapshots__/CardPathfinder.test.js.snap
  components/cards/stories/Events/Story1.vue
  components/cards/stories/Events/Story2.vue
  components/cards/stories/GenericCard/Story1.vue
  components/cards/stories/GenericCard/Story4.vue
  components/cards/stories/GenericCard/Story5.vue
  components/cards/stories/GenericCard/Story6.vue
  components/cards/stories/GenericCard/Story7.vue
  components/cards/stories/News/Story4.vue
  components/forms/stories/InlineForm.vue
  components/forms/stories/InlineSearchForm.vue
  components/forms/stories/InlineSearchFormInverse.vue
  components/forms/stories/InlineSearchFormMin.vue
  components/icons/stories/FindACourseSpritesheet.vue
  components/icons/stories/Sprite.vue
  components/quick-links-menu/QuickLinksMenuItem.vue
  components/quick-links-menu/QuickLinksSecondaryItem.vue
  components/quick-links-menu/__tests__/__snapshots__/QuickLinksMenuItem.test.js.snap
  components/quick-links-menu/__tests__/__snapshots__/QuickLinksSecondaryItem.test.js.snap
  components/side-panel/SidePanel.vue
  components/side-panel/SidePanelNavItem.vue
  components/side-panel/__tests__/__snapshots__/SidePanel.test.js.snap
  components/side-panel/__tests__/__snapshots__/SidePanelNavItem.test.js.snap
  components/sidebar/Sidebar.vue
  components/sidebar/__tests__/__snapshots__/Sidebar.test.js.snap
  components/sublink-menu/SublinkMenu.vue
  components/sublink-menu/SublinkMenuItem.vue
  components/sublink-menu/__tests__/__snapshots__/SublinkMenuItem.test.js.snap
Labels: pr-patch

#1262 chore(linting) Remove rule for @ rule to be at end of class
  .stylelintrc
Labels: pr-patch

#1263 feat(component): logo listing
  components/listing/LogoListing.vue
  components/listing/__tests__/LogoListing.test.js
  components/listing/__tests__/__snapshots__/LogoListing.test.js.snap
  components/listing/_logo-listing.css
  components/listing/index.css
  components/listing/sample.json
  components/listing/stories/Container/LogoListing.vue
  components/listing/stories/Container/index.js
  targets/lib/index.js
  targets/vue/index.js
Labels: pr-minor

#1264 fix(component): mega menu title identifier line IE11
  components/megamenu/MegaMenu.vue
  components/megamenu/_mega-menu-title.css
  components/megamenu/_mega-menu.css
Labels: pr-patch

#1215 feature(component): media gallery
  components/_base.css
  components/_utils.css
  components/_vars.css
  components/cards/_card-generic.css
  components/index.css
  components/media-gallery/MediaGallery.vue
  components/media-gallery/ThumbnailGallery.vue
  components/media-gallery/__tests__/MediaGallery.test.js
  components/media-gallery/__tests__/ThumbnailGallery.test.js
  components/media-gallery/__tests__/__snapshots__/MediaGallery.test.js.snap
  components/media-gallery/__tests__/__snapshots__/ThumbnailGallery.test.js.snap
  components/media-gallery/_media-gallery.css
  components/media-gallery/_thumbnails.css
  components/media-gallery/index.css
  components/media-gallery/inpage-sample.json
  components/media-gallery/sample.json
  components/media-gallery/stories/MediaGalleryInPage.vue
  components/media-gallery/stories/MediaGalleryOverlay2.vue
  components/media-gallery/stories/MediaGalleryOverlay3.vue
  components/media-gallery/stories/MediaGalleryOverlay4.vue
  components/media-gallery/stories/MediaGalleryOverlayWithCaption2.vue
  components/media-gallery/stories/MediaGalleryOverlayWithCaption3.vue
  components/media-gallery/stories/MediaGalleryOverlayWithCaption4.vue
  components/media-gallery/stories/MediaGalleryThumbnails2.vue
  components/media-gallery/stories/MediaGalleryThumbnails3.vue
  components/media-gallery/stories/MediaGalleryThumbnails4.vue
  components/media-gallery/stories/index.js
  components/media-gallery/stories/media-gallery-overlay.md
  components/media-gallery/stories/media-gallery.md
  components/media-gallery/stories/thumbnails.md
  components/media-gallery/thumbnails-sample.json
  components/photo-gallery/stories/index.js
  targets/lib/index.js
Labels: pr-minor

#1267 feat(filter): accordion redesign
  components/filter/__tests__/__snapshots__/AccordionFilter.test.js.snap
  components/filter/accordion/AccordionFilter.vue
Labels: pr-patch
