Repository unimelb/pattern-lib, pull requests merged in 2019-07, with the labels that each got.

#1163 chore(z-index): tidy up z-index ordering
  components/_vars.css
  components/cards/_card-image-focus.css
  components/focus-wrapper/index.css
  components/footer/index.css
  components/forms/_select.css
  components/header/index.css
  components/megamenu/_mega-menu.css
  components/modal/index.css
  components/nav-bar/index.css
  components/nav/_page-nav.css
  components/navigation/index.css
  components/search/_blanket.css
  components/search/_header-tools.css
  components/timeline/index.css
  components/toggle/index.css
Labels: pr-patch

#1187 chore(console) Add command to stop vue-axe clearing console
  .storybook/config.js
Labels: Review Wanted

#1180 upgrade(dependencies): minor update wth backward-compatible/features
  package.json
  yarn.lock
Labels: pr-patch

#1197 chore(component): carousel
  components/buttons/ButtonIcon.vue
  components/carousel/Carousel.vue
  components/carousel/__tests__/Carousel.test.js
  components/carousel/__tests__/__snapshots__/Carousel.test.js.snap
  components/carousel/index.css
  components/carousel/sample.json
  components/carousel/stories/CarouselDefault.vue
  components/carousel/stories/CarouselLongTiming.vue
  components/carousel/stories/carousel-doc.md
  components/carousel/stories/index.js
  components/icons/sprite/index.js
  components/icons/sprite/pause.svg
  components/icons/stories/Sprite.vue
  components/index.css
  package.json
  targets/lib/index.js
  targets/vue/index.js
  yarn.lock
Labels: pr-minor

#1204 update(component): carousel redesign
  components/_vars.css
  components/carousel/Carousel.vue
  components/carousel/__tests__/__snapshots__/Carousel.test.js.snap
  components/carousel/index.css
  components/carousel/sample.json
  components/carousel/stories/carousel-doc.md
Labels: pr-patch

#1199 feat(filter): cards and accordion hard coded filter
  components/_utils.css
  components/_vars.css
  components/dropdown/stories/index.js
  components/filter/__tests__/AccordionFilter.test.js
  components/filter/__tests__/CardsFilter.test.js
  components/filter/__tests__/__snapshots__/AccordionFilter.test.js.snap
  components/filter/__tests__/__snapshots__/CardsFilter.test.js.snap
  components/filter/accordion/AccordionFilter.vue
  components/filter/accordion/accordion.md
  components/filter/accordion/accordionCMS.md
  components/filter/accordion/data.json
  components/filter/cards/CardsFilter.vue
  components/filter/cards/cards.md
  components/filter/cards/cardsCMS.md
  components/filter/cards/data.json
  components/filter/filters-core/filters/DropdownFilter.vue
  components/filter/filters-core/results-count/FilterResultsCount.vue
  components/filter/filters-core/results-count/index.css
  components/filter/filters-core/results/FilterResults.vue
  components/filter/index.css
  components/filter/stories/AccordionFilterStory.vue
  components/filter/stories/AccordionFilterStoryCMS.vue
  components/filter/stories/CardsFilterStory.vue
  components/filter/stories/CardsFilterStoryCMS.vue
  components/filter/stories/index.js
  components/forms/_select.css
  components/index.css
  targets/lib/index.js
  targets/vue/index.js
Labels: pr-minor

#1189 feat(component): tags - news tag
  components/cards/CardNewsTag.vue
  components/cards/GenericCard.vue
  components/cards/__tests__/__snapshots__/CardEvents.test.js.snap
  components/cards/__tests__/__snapshots__/GenericCard.test.js.snap
  components/cards/_card-events.css
  components/cards/_card-features-panel.css
  components/cards/_card-generic.css
  components/cards/_card-showcase-profile.css
  components/cards/_card-stafflist.css
  components/cards/stories/Events/Story2.vue
  components/cards/stories/GenericCard/Story1.vue
  components/cards/stories/GenericCard/Story6.vue
  components/cards/stories/GenericCard/Story7.vue
  components/cards/stories/News/Story4.vue
  components/cards/stories/News/index.js
  components/cards/stories/News/news.md
  components/filter/__tests__/__snapshots__/CardsFilter.test.js.snap
  components/index.css
  components/tags/Tags.vue
  components/tags/__tests__/Tags.test.js
  components/tags/__tests__/__snapshots__/Tags.test.js.snap
  components/tags/index.css
  components/tags/stories/Story1.vue
  components/tags/stories/index.js
  components/tags/stories/tags.md
  targets/lib/index.js
  targets/vue/index.js
Labels: Review Wanted

#1211 fix(css): redundant prop
  components/cards/_card-events.css
Labels: pr-patch

#1212 fix(component): mega menu title
  components/megamenu/_mega-menu-title.css
Labels: pr-patch

#1213 chore(component): channel bar titles
  components/social-media-bar/SocialMediaBar.vue
  components/social-media-bar/__tests__/__snapshots__/SocialMediaBar.test.js.snap
  components/social-media-bar/index.css
  components/social-media-bar/stories/SocialMediaBarDefault.vue
Labels: Review Wanted
