Repository unimelb/pattern-lib, pull requests merged in 2020-09, with the labels that each got.

#1496 chore(component): mega menu hover delay
  components/megamenu/MegaMenu.vue
  components/megamenu/_mega-menu-top.css
  components/megamenu/_mega-menu.css
  components/megamenu/stories/HybridMenu.vue
  components/megamenu/stories/HybridMenuWithTopNav.vue
  constants/timers.js
Labels: Review Wanted

#1497 chore(component): remove focuswrapper size options, small styling changes
  .vscode/settings.json
  components/_utils.css
  components/_vars.css
  components/cards/CardFocusBox.vue
  components/cards/CardPathfinder.vue
  components/cards/CardStat.vue
  components/cards/_card-focus-box.css
  components/cards/_card.css
  components/cards/stories/FocusBox/Story1.vue
  components/focus-wrapper/FocusWrapper.vue
  components/focus-wrapper/__tests__/FocusWrapper.test.js
  components/focus-wrapper/index.css
  components/focus-wrapper/stories/Story3.vue
  components/focus-wrapper/stories/Story6.vue
  components/focus-wrapper/stories/index.js
  components/navigation/InPageNavigation.vue
  components/print.css
  components/profiles/alumni-profiles/AlumniProfiles.vue
  components/section/SplitSectionQuote.vue
  components/section/__tests__/__snapshots__/SplitSectionQuote.test.js.snap
  components/section/_split-section.css
  components/section/_two-column-header-text.css
  components/section/stories/SectionTwo/Story6.vue
  components/testimonials/Testimonials.vue
  components/typography/_headings.css
Labels: breaking change, chore, design, pr-major

#1500 chore(package): delete package json
  package-lock.json
Labels: pr-patch

#1359 chore(upgrade) postcss preset env
  .browserslistrc
  .storybook/decorators/PageDecorator.vue
  components/_utils.css
  components/buttons/index.css
  components/cards/_card-pathfinder.css
  components/cards/_card-stat.css
  components/cards/_card.css
  components/carousel/sample.json
  components/download-block/stories/DownloadBlockDefault.vue
  components/figure/_figure-wrap.css
  components/forms/_controls.css
  components/forms/_inline.css
  components/forms/_select.css
  components/forms/_text.css
  components/header/page-header.css
  components/header/split-section-header.css
  components/header/stories/level-1/Level1Default.vue
  components/header/stories/level-1/Level1DualEntity.vue
  components/header/stories/level-1/Level1Entity.vue
  components/header/stories/level-1/Level1Home.vue
  components/header/stories/level-1/Level1HomeCampaignButton.vue
  components/header/stories/level-1/Level1HomeCampaignNoLogo.vue
  components/header/stories/level-1/Level1HomeCampaignOverlay25.vue
  components/header/stories/level-1/Level1HomeCampaignOverlay50.vue
  components/header/stories/level-1/Level1HomeCampaignOverlay75.vue
  components/header/stories/level-2/Level2CampaignNoLogo.vue
  components/header/stories/level-2/Level2CampaignOverlay50.vue
  components/header/stories/level-2/Level2Default.vue
  components/header/stories/level-2/Level2DualEntity.vue
  components/header/stories/level-2/Level2Entity.vue
  components/header/stories/split-section/Default.vue
  components/megamenu/_mega-menu-top.css
  components/megamenu/stories/MegaMenuExpanded.vue
  components/megamenu/stories/MegaMenuTitle.vue
  components/notice/index.css
  components/screen-reader-jump-to/stories/Default.vue
  components/section/_split-section.css
  components/social-media-bar/index.css
  components/timeline/stories/Story3.vue
  components/toggle/index.css
  package.json
  postcss.config.js
  yarn.lock
Labels: pr-minor

#1503 chore(footer): update virtual campus link
  components/footer/PageFooterSitemap.vue
Labels: pr-patch

#1509 chore(docs): Update how to use the library
  README.md
  components/cards/CardFeaturesPanel.vue
  components/cards/__tests__/CardFeaturesPanel.test.js
  docs/how-to-use.md
Labels: pr-patch

#1510 fix(component): amend banner heights, font sizing, text alignment for Campaign Banner 2021
  components/campaign/_campaign-banner.css
Labels: bug, pr-patch

#1512 chore(css): add focus wrapper deprecated classes back
  components/_utils.css
  components/cards/_card-focus-box.css
  components/print.css
Labels: pr-patch

#1514 fix(component): accordion with big content
  components/toggle/index.css
Labels: Review Wanted
