Repository unimelb/pattern-lib, pull requests merged in 2020-08, with the labels that each got.

#1466 feat(component): button card
  components/buttons/ButtonCard.vue
  components/buttons/index.css
  components/buttons/stories/StoryButtonCard.vue
  components/buttons/stories/index.js
  components/profiles/stories/Accordion.vue
  targets/lib/index.js
  targets/vue/index.js
Labels: pr-minor

#1468 feat(component): rounded figure and new section
  components/figure/FigureRounded.vue
  components/figure/_figure-wrap.css
  components/figure/stories/Story20.vue
  components/figure/stories/index.js
  components/section/_two-column-round-image.css
  components/section/index.css
  components/section/stories/SectionTwo/Story5.vue
  components/section/stories/SectionTwo/index.js
  targets/lib/index.js
  targets/vue/index.js
Labels: pr-minor

#1470 Print style for About site & Study site
  components/index.css
  components/print.css
Labels: pr-minor

#1469 feat(component): header text with cta 2 column
  components/_vars.css
  components/section/_two-column-header-text.css
  components/section/index.css
  components/section/stories/SectionTwo/Story6.vue
  components/section/stories/SectionTwo/index.js
Labels: pr-minor

#1472 feat(component): card rounded figure
  components/_grid.css
  components/cards/CardFeaturesPanel.vue
  components/cards/CardRoundedFigure.vue
  components/cards/__tests__/__snapshots__/CardFeaturesPanel.test.js.snap
  components/cards/_card-rounded-figure.css
  components/cards/index.css
  components/cards/stories/FeaturesPanel/Story1.vue
  components/cards/stories/FeaturesPanel/Story2.vue
  components/cards/stories/FeaturesPanel/Story3.vue
  components/cards/stories/RoundedFigure/Story1.vue
  components/cards/stories/RoundedFigure/index.js
  components/cards/stories/index.js
  components/figure/FigureRounded.vue
  components/figure/_figure-wrap.css
  components/figure/stories/Story20.vue
  targets/lib/index.js
  targets/vue/index.js
Labels: pr-minor

#1475 feat(component): redesign features panel
  components/cards/CardFeaturesPanel.vue
  components/cards/__tests__/CardFeaturesPanel.test.js
  components/cards/_card-features-panel.css
  components/cards/stories/FeaturesPanel/Story4.vue
  components/cards/stories/FeaturesPanel/index.js
Labels: pr-patch

#1473 fix(component): Screen Reader Jump To main content
  components/buttons/ButtonIcon.vue
  components/screen-reader-jump-to/ScreenReaderJumpTo.vue
  components/screen-reader-jump-to/index.css
  components/screen-reader-jump-to/stories/Default.vue
  components/screen-reader-jump-to/stories/screenReaderMd.md
Labels: pr-patch

#1478 fix(warn): vue tip and warn
  components/filters/components/filter-dropdown/FilterDropdown.vue
  components/filters/components/filter-dropdown/__tests__/__snapshots__/FilterDropdown.test.js.snap
  components/screen-reader-jump-to/ScreenReaderJumpTo.vue
Labels: pr-patch

#1471 feat(component): todo list
  components/buttons/index.css
  components/index.css
  components/section/_two-column-round-image.css
  components/todo-list/README.md
  components/todo-list/TodoList.vue
  components/todo-list/__tests__/TodoList.test.js
  components/todo-list/__tests__/__snapshots__/TodoList.test.js.snap
  components/todo-list/index.css
  components/todo-list/stories/Default.vue
  components/todo-list/stories/index.js
  targets/lib/index.js
  targets/vue/index.js
Labels: pr-major

#1476 fix(component): split section order bug
  components/cards/_card-rounded-figure.css
  components/section/_split-section.css
  components/todo-list/TodoList.vue
Labels: pr-patch

#1474 feat(component): Campaign Banner
  components/campaign/CampaignBanner.vue
  components/campaign/__tests__/CampaignBanner.test.js
  components/campaign/__tests__/__snapshots__/CampaignBanner.test.js.snap
  components/campaign/_campaign-banner.css
  components/campaign/index.css
  components/campaign/stories/CampaignBanner2021.vue
  components/campaign/stories/CampaignBanner2021NoButton.vue
  components/campaign/stories/campaign-banner.md
  components/campaign/stories/index.js
  components/campaign/stories/static/1440w_campaign_banner.jpg
  components/campaign/stories/static/320w_campaign_banner.jpg
  components/campaign/stories/static/768w_campaign_banner.jpg
  targets/lib/index.js
  targets/vue/index.js
Labels: pr-minor

#1479 feat(component): card image page listing
  components/cards/CardImageListing.vue
  components/cards/_card-image-listing.css
  components/cards/index.css
  components/cards/stories/ImageListing/Story1.vue
  components/cards/stories/ImageListing/Story2.vue
  components/cards/stories/ImageListing/index.js
  components/cards/stories/index.js
  targets/lib/index.js
  targets/vue/index.js
Labels: pr-minor

#1482 Amend paragraph text width
  components/campaign/_campaign-banner.css
Labels: bug, pr-patch

#1484 feat(component): 3 column section and colour helpers
  components/_utils.css
  components/_vars.css
  components/helpers/stories/Colours.vue
  components/section/stories/SectionThree/Story1.vue
  components/section/stories/SectionThree/index.js
  components/section/stories/index.js
Labels: pr-minor

#1485 Reduce padding-top on split section text container
  components/section/_split-section.css
Labels: pr-patch

#1488 chore(component): colour check
  .storybook/config.js
  components/_utils.css
  components/block-quotation/index.css
  components/breadcrumbs/index.css
  components/campaign/index.css
  components/cards/_card-generic.css
  components/cards/_card-imagelist.css
  components/cards/_card-news.css
  components/cards/_card.css
  components/cards/stories/RoundedFigure/Story1.vue
  components/download-block/index.css
  components/filter/filters-core/results-count/index.css
  components/filters/components/filtered-results/index.css
  components/forms/_select.css
  components/header/page-header-event.css
  components/section/stories/SectionThree/Story1.vue
  components/sidebar/index.css
  components/sublink-menu/index.css
  components/sublink-menu/stories/SublinkMenuWithImageCard.vue
Labels: Review Wanted, pr-patch

#1487 feat(colours): typography overhaul
  .storybook/config.js
  components/_base.css
  components/_utils.css
  components/block-quotation/index.css
  components/breadcrumbs/index.css
  components/campaign/index.css
  components/cards/_card-contact.css
  components/cards/_card-generic.css
  components/cards/_card-imagelist.css
  components/cards/_card-link.css
  components/cards/_card-news.css
  components/cards/_card.css
  components/cards/stories/RoundedFigure/Story1.vue
  components/download-block/index.css
  components/filter/filters-core/results-count/index.css
  components/filters/components/filtered-results/index.css
  components/forms/_select.css
  components/header/page-header-event.css
  components/print.css
  components/section/stories/SectionThree/Story1.vue
  components/sidebar/index.css
  components/sublink-menu/index.css
  components/sublink-menu/stories/SublinkMenuWithImageCard.vue
Labels: pr-patch

#1483 Enhance CampaignBanner component in the way to take numerous background sources
  components/campaign/CampaignBanner.vue
  components/campaign/__tests__/CampaignBanner.test.js
  components/campaign/__tests__/__snapshots__/CampaignBanner.test.js.snap
  components/campaign/_campaign-banner.css
  components/campaign/stories/CampaignBanner2021.vue
  components/campaign/stories/CampaignBanner2021NoButton.vue
  components/campaign/stories/campaign-banner.md
  components/campaign/stories/static/1440w_campaign_banner_2x.jpg
  components/campaign/stories/static/320w_campaign_banner_2x.jpg
  components/campaign/stories/static/320w_campaign_banner_3x.jpg
  components/campaign/stories/static/768w_campaign_banner_2x.jpg
  helpers/viewports.js
  package.json
Labels: pr-minor

#1490 chore(component): card image link
  components/cards/CardImageLink.vue
  components/cards/CardImageListing.vue
  components/cards/_card-image-link.css
  components/cards/index.css
  components/cards/stories/ImageLink/Story1.vue
  components/cards/stories/ImageLink/Story2.vue
  components/cards/stories/ImageLink/index.js
  components/cards/stories/index.js
  targets/lib/index.js
  targets/vue/index.js
Labels: pr-minor

#1491 fix(styling): various alignment, spacing and colour tweaks
  components/campaign/CampaignBanner.vue
  components/campaign/__tests__/__snapshots__/CampaignBanner.test.js.snap
  components/campaign/_campaign-banner.css
  components/cards/_card-generic.css
  components/section/_split-section.css
  components/section/_two-column-header-text.css
  components/sublink-menu/index.css
Labels: pr-patch

#1493 fix(styling): text contrast fixes
  components/_base.css
  components/_vars.css
Labels: accessibility, pr-patch
