Repository unimelb/pattern-lib, pull requests merged in 2021-03, with the labels that each got.

#1554 chore(vars): update
  components/_vars.css
  components/header/page-header-event.css
Labels: pr-patch

#1555 fix(component): button secondary border colour
  components/buttons/index.css
Labels: pr-patch

#1557 fix(component): footer accessibility requests
  components/footer/index.css
Labels: pr-patch

#1561 fix(component): modal input trap
  components/modal/ModalDialog.vue
Labels: pr-patch

#1506 refactor(component): card division to use focus wrapper
  components/cards/CardDivisionHead.vue
  components/cards/__tests__/__snapshots__/CardDivisionHead.test.js.snap
  components/cards/_card-division.css
Labels: Review Wanted, pr-major

#1556 Colour tweaks from Today
  components/_base.css
  components/_utils.css
  components/_vars.css
  components/block-quotation/index.css
  components/cards/_card-fact.css
  components/filters/components/filter-dropdown/index.css
  components/forms/_form.css
  components/forms/_select.css
  components/header/page-header.css
  components/media-gallery/_thumbnails.css
  components/profiles/accordion-profile/index.css
  components/section/_split-section.css
  components/stats/index.css
  components/tabs/index.css
  components/timeline/index.css
  components/typography/_headings.css
  components/typography/_ol-giant.css
  components/typography/stories/TypeClassesToday.vue
  components/typography/stories/index.js
Labels: Review Wanted, accessibility, design

#1560 fix(bugs): various small issues
  UPGRADE.md
  components/_base.css
  components/document-list/_document-list.css
  components/error-box/index.css
  components/figure/_figure-wrap.css
  components/footer/PageFooterUpper.vue
  components/header/PageHeader.vue
  components/header/PageHeaderMin.vue
  components/header/stories/level-1/Level1Home.vue
  components/header/stories/level-1/Level1HomeCampaignButton.vue
  components/header/stories/level-1/Level1HomeCampaignOverlay25.vue
  components/header/stories/level-1/Level1HomeCampaignOverlay50.vue
  components/header/stories/level-1/Level1HomeCampaignOverlay75.vue
  components/header/stories/level-2/Level2CampaignOverlay50.vue
  components/logo/Logo.vue
  components/logo/__tests__/Logo.test.js
  components/logo/index.css
  components/logo/stories/NoPadding.vue
  components/logo/stories/index.js
  components/logo/stories/logo.md
  components/megamenu/stories/HeaderFullwidth.vue
  components/notice/stories/NoticeDanger.vue
  components/section/SectionDivider.vue
  components/section/__tests__/__snapshots__/SectionDivider.test.js.snap
  components/section/stories/Crest/Story1.vue
Labels: pr-patch

#1562 chore(component): toggle block scroll tweaks
  components/toggle/ToggleBlock.vue
  components/toggle/ToggleBlockMobile.vue
  components/toggle/index.css
Labels: pr-patch

#1569 fix accessibility role menuitem
  components/megamenu/MegaMenu.vue
Labels: pr-patch

#1565 fix(component): mega menu mobile viewport checker
  components/megamenu/MegaMenu.vue
  helpers/isMobile.js
Labels: pr-patch

#1570 fix accessibility svg aria label
  components/breadcrumbs/PageBreadcrumbs.vue
  components/cards/CardLink.vue
  components/cards/CardStaffList.vue
  components/filter/accordion/AccordionFilter.vue
  components/filter/cards-category/CardsFilterCategory.vue
  components/filter/cards/CardsFilter.vue
  components/filter/courses/CoursesFilter.vue
  components/filters/components/filter-dropdown/FilterDropdown.vue
  components/focus-wrapper/FocusWrapper.vue
  components/footer/PageFooterUpper.vue
  components/megamenu/MegaMenu.vue
  components/navigation/InPageNavigation.vue
  components/profiles/accordion-profile/AccordionProfile.vue
  components/quick-links-menu/QuickLinksMenuItem.vue
  components/search/PageSearch.vue
  components/search/PageSearchForm.vue
  components/side-panel/SidePanel.vue
  components/side-panel/SidePanelNavItem.vue
  components/social-media-bar/SocialMediaBar.vue
  components/sublink-menu/SublinkMenuItem.vue
Labels: pr-patch
