Repository unimelb/pattern-lib, pull requests merged in 2021-06, with the labels that each got.

#1646 fix(component): testimonials quote
  components/testimonials/_testimonials-alt.css
Labels: Review Wanted, pr-patch

#1647 fix(component): mega menu duplicated id with icon-menu
  components/megamenu/MegaMenu.vue
Labels: Review Wanted, accessibility, pr-patch

#1645 fix(component): three column link to sticky to bottom
  components/section/_section-alt.css
  components/section/_section.css
  components/section/stories/SectionThree/Story1.vue
  components/today/stories/Section/ThreeUp.vue
Labels: Review Wanted, cms, pr-patch

#1649 fix(accessibility): Override Normalize styles to browser defaults for Firefox focus rings
  components/_base.css
Labels: pr-patch

#1655 fix(component): breadcrumbs accessibility
  components/breadcrumbs/PageBreadcrumbs.vue
  components/breadcrumbs/__tests__/__snapshots__/PageBreadcrumbs.test.js.snap
Labels: Review Wanted, pr-patch

#1659 fix(component): skip to content and icons injection
  .storybook/webpack.config.js
  components/screen-reader-jump-to/stories/Default.vue
  package.json
  targets/lib/index.css
  targets/lib/index.js
  targets/lib/webpack.config.shared.js
  yarn.lock
Labels: Review Wanted, pr-minor

#1657 fix(component): section alt icons
  components/section/_section-alt.css
  components/today/stories/Section/StandardWithColumns.vue
  components/today/stories/Section/ThreeUp.vue
Labels: Review Wanted, pr-patch

#1669 Update VideoPlayer component to remove DOM issues in Nuxt SSR
  components/embed/VideoPlayer.vue
  components/embed/__tests__/__snapshots__/VideoPlayer.test.js.snap
Labels: pr-patch

#1671 chore(component): mega menu alt tweaks
  components/megamenu/_mega-menu-alt.css
Labels: pr-patch

#1672 Fix padding for sections in succession
  components/section/_section-alt.css
Labels: pr-patch

#1674 fix(component): pathfinder mobile issue
  components/buttons/index.css
  components/today/PathfinderToday/index.css
Labels: pr-patch

#1675 fix(css): for today sections
  components/_utils.css
  components/section/_section-alt.css
  components/testimonials/_testimonials-alt.css
Labels: pr-patch

#1676 fix(accessibility): Add left border to notices to meet non-text contrast requirements
  components/notice/index.css
Labels: pr-patch

#1677 chore(component): add new course card type option for colour
  components/cards/_card-course.css
  components/cards/stories/Course/Story2.vue
  components/cards/stories/Course/card-course-list.md
  components/cards/stories/Course/card-course.md
Labels: pr-patch

#1681 chore(input): implement base input styling
  components/_base.css
Labels: pr-patch
