Repository unimelb/pattern-lib, pull requests merged in 2021-05, with the labels that each got.

#1596 Add new button styles
  components/buttons/index.css
  components/buttons/stories/StoryButtonText.vue
  components/buttons/stories/index.js
Labels: pr-patch

#1600 (chore): svg - amend envelope.svg to remove unnecessary properties
  components/icons/sprite/envelope.svg
Labels: accessibility, bug, chore, pr-patch

#1601 (chore): footer - update reconciliation link
  components/footer/PageFooter.vue
  components/footer/__tests__/__snapshots__/PageFooter.test.js.snap
Labels: chore, pr-patch

#1602 (chore): stories - remove outdated manual markup
  components/cards/stories/ImageList/focus-image-docs.md
Labels: pr-patch

#1604 remove(search): from page footer
  components/footer/PageFooterUpper.vue
  components/footer/index.css
Labels: pr-patch

#1606 remove(component): toggleblock from footer
  components/footer/PageFooter.vue
Labels: pr-patch

#1610 fix(component): tabs console issue
  components/tabs/Tabs.vue
Labels: pr-patch

#1616 fix accessibility svg role
  components/quick-links-menu/QuickLinksMenuItem.vue
Labels: pr-patch

#1599 Add new video components and new icon for play button
  components/embed/Video.vue
  components/embed/VideoFullWidth.vue
  components/embed/__tests__/Video.test.js
  components/embed/__tests__/__snapshots__/Video.test.js.snap
  components/embed/_embed.css
  components/embed/_video-full-width.css
  components/embed/_video.css
  components/embed/index.css
  components/embed/index.js
  components/embed/stories/FullWidthVideo.vue
  components/embed/stories/VideoLandscape.vue
  components/embed/stories/VideoPortrait.vue
  components/embed/stories/index.js
  components/embed/stories/video.md
  components/icons/sprite/index.js
  components/icons/sprite/play-circle.svg
  components/icons/stories/Sprite.vue
  targets/lib/index.js
  targets/vue/index.js
Labels: pr-major

#1598 Feature/page footer today
  components/_grid.css
  components/buttons/index.css
  components/footer/PageFooterAlt.vue
  components/footer/__tests__/PageFooterAlt.test.js
  components/footer/__tests__/__snapshots__/PageFooterAlt.test.js.snap
  components/footer/_page-footer-alt.css
  components/footer/_page-footer.css
  components/footer/index.css
  components/footer/index.js
  components/footer/stories/PageFooterAlt.vue
  components/footer/stories/index.js
  targets/lib/index.js
  targets/vue/index.js
Labels: pr-major

#1617 fix(storybook): preview config
  .storybook/preview-head.html
  components/accessibility/stories/HiddenPageResources.vue
  components/accessibility/stories/index.js
  components/modal/ModalDialog.vue
  components/modal/__tests__/__snapshots__/ModalDialog.test.js.snap
Labels: cms, pr-patch

#1611 New sections from Today
  .storybook/config.js
  .storybook/utils/create-story.js
  components/_utils.css
  components/icons/sprite/briefcase.svg
  components/icons/sprite/check.svg
  components/icons/sprite/handshake.svg
  components/icons/sprite/index.js
  components/icons/stories/Sprite.vue
  components/section/SectionAlt.vue
  components/section/__tests__/SectionAlt.test.js
  components/section/__tests__/__snapshots__/SectionAlt.test.js.snap
  components/section/_section-alt.css
  components/section/index.css
  components/today/stories/Section/Columns.vue
  components/today/stories/Section/SectionAlt.md
  components/today/stories/Section/StandardWithColumns.vue
  components/today/stories/Section/StandardWithImage.vue
  components/today/stories/Section/ThreeUp.vue
  components/today/stories/Section/index.js
  components/today/stories/index.js
  targets/lib/index.js
  targets/vue/index.js
Labels: accessibility, pr-minor

#1620 Add bordered section to the docs, update mobile spacing
  components/_shims.css
  components/helpers/stories/ShimMb.vue
  components/section/_section-alt.css
  components/today/stories/Section/Bordered.vue
  components/today/stories/Section/Columns.vue
  components/today/stories/Section/StandardWithColumns.vue
  components/today/stories/Section/ThreeUp.vue
  components/today/stories/Section/index.js
Labels: pr-patch

#1621 fix(component): video naming
  components/embed/VideoFullWidth.vue
  components/embed/VideoPlayer.vue
  components/embed/__tests__/VideoPlayer.test.js
  components/embed/__tests__/__snapshots__/VideoPlayer.test.js.snap
  components/embed/stories/VideoLandscape.vue
  components/embed/stories/VideoPortrait.vue
  components/embed/stories/video.md
  targets/lib/index.js
  targets/vue/index.js
Labels: bug, pr-patch

#1613 feat(component): quick links alt
  components/quick-links-menu/QuickLinksAlt.vue
  components/quick-links-menu/__tests__/QuickLinksAlt.test.js
  components/quick-links-menu/__tests__/__snapshots__/QuickLinksAlt.test.js.snap
  components/quick-links-menu/_quick-links-alt.css
  components/quick-links-menu/index.css
  components/today/stories/QuickLinksMenu/Buttons.vue
  components/today/stories/QuickLinksMenu/Links.vue
  components/today/stories/QuickLinksMenu/Variations.vue
  components/today/stories/QuickLinksMenu/index.js
  components/today/stories/QuickLinksMenu/quick-links-alt.md
  components/today/stories/index.js
  targets/lib/index.js
  targets/vue/index.js
Labels: pr-minor

#1612 feat(component): pathfinder today
  components/forms/_text.css
  components/index.css
  components/today/PathfinderToday/PathfinderToday.vue
  components/today/PathfinderToday/__tests__/PathfinderToday.test.js
  components/today/PathfinderToday/__tests__/__snapshots__/PathfinderToday.test.js.snap
  components/today/PathfinderToday/index.css
  components/today/PathfinderToday/stories/PathfinderToday.md
  components/today/PathfinderToday/stories/Story1.vue
  components/today/PathfinderToday/stories/Story2.vue
  components/today/PathfinderToday/stories/Story3.vue
  components/today/PathfinderToday/stories/index.js
  targets/lib/index.js
  targets/vue/index.js
Labels: pr-minor

#1603 Add new inline search component and alternative search icon
  components/_vars.css
  components/forms/InlineSearch.vue
  components/forms/__tests__/InlineSearch.test.js
  components/forms/__tests__/__snapshots__/InlineSearch.test.js.snap
  components/forms/_inline-search.css
  components/forms/index.css
  components/forms/stories/InlineSearchTodayDarkBg.vue
  components/forms/stories/InlineSearchTodayNoButton.vue
  components/forms/stories/InlineSearchTodaySubmit.vue
  components/forms/stories/index.js
  components/forms/stories/inline-search.md
  components/icons/sprite/search.svg
  components/today/PathfinderToday/PathfinderToday.vue
  components/today/PathfinderToday/stories/Story3.vue
  targets/lib/index.js
  targets/vue/index.js
Labels: pr-minor

#1622 fix(component): section with icons to use div wrapper
  components/section/_section-alt.css
  components/today/stories/Section/StandardWithColumns.vue
  components/today/stories/Section/ThreeUp.vue
Labels: pr-patch

#1624 Add course index
  components/cards/_card-course.css
  components/today/stories/Section/CourseIndex.vue
  components/today/stories/Section/index.js
Labels: Review Wanted, pr-minor

#1625 fix(section): alt svg
  components/section/_section-alt.css
  components/today/stories/Section/StandardWithColumns.vue
  components/today/stories/Section/ThreeUp.vue
Labels: pr-patch

#1619 feat(component): testimonials alt
  components/_grid.css
  components/embed/VideoPlayer.vue
  components/embed/__tests__/__snapshots__/VideoPlayer.test.js.snap
  components/embed/stories/video.md
  components/testimonials/TestimonialsAlt.vue
  components/testimonials/__tests__/TestimonialsAlt.test.js
  components/testimonials/__tests__/__snapshots__/TestimonialsAlt.test.js.snap
  components/testimonials/_testimonials-alt.css
  components/testimonials/_testimonials.css
  components/testimonials/index.css
  components/testimonials/index.js
  components/today/stories/Section/TestimonialsText.vue
  components/today/stories/Section/TestimonialsTextLong.vue
  components/today/stories/Section/TestimonialsVideo.vue
  components/today/stories/Section/index.js
  components/today/stories/Testimonials/Text.vue
  components/today/stories/Testimonials/TextLong.vue
  components/today/stories/Testimonials/Videos.vue
  components/today/stories/Testimonials/index.js
  components/today/stories/Testimonials/testimonials-alt.md
  components/today/stories/index.js
  targets/lib/index.js
  targets/vue/index.js
Labels: accessibility, pr-minor

#1623 Add new component for section image and document use of quick links
  components/section/SectionImage.vue
  components/section/__tests__/SectionImage.test.js
  components/section/__tests__/__snapshots__/SectionImage.test.js.snap
  components/section/_section-image.css
  components/section/index.css
  components/today/stories/Section/QuickLinks.vue
  components/today/stories/Section/SectionImage.md
  components/today/stories/Section/index.js
  targets/lib/index.js
  targets/vue/index.js
Labels: accessibility, pr-minor

#1615 feat(component): page header alt, page header study and campaign banner alt
  components/campaign/CampaignBannerAlt.vue
  components/campaign/__tests__/CampaignBannerAlt.test.js
  components/campaign/__tests__/__snapshots__/CampaignBannerAlt.test.js.snap
  components/campaign/_campaign-banner-alt.css
  components/campaign/index.css
  components/header/PageHeaderAlt.vue
  components/header/PageHeaderStudy.vue
  components/header/_page-header-alt.css
  components/header/_page-header-study.css
  components/header/index.css
  components/today/PathfinderToday/stories/Story3.vue
  components/today/stories/Campaign/Default.vue
  components/today/stories/Campaign/Event.vue
  components/today/stories/Campaign/Large.vue
  components/today/stories/Campaign/LargeWithLinks.vue
  components/today/stories/Campaign/campaign-banner-alt.md
  components/today/stories/Campaign/index.js
  components/today/stories/Campaign/static/campaign-hero-desktop-2.png
  components/today/stories/Campaign/static/campaign-hero-desktop.jpg
  components/today/stories/Campaign/static/campaign-hero-mobile-2.png
  components/today/stories/Campaign/static/campaign-hero-mobile.png
  components/today/stories/Header/Default.vue
  components/today/stories/Header/DefaultDark.vue
  components/today/stories/Header/Study.vue
  components/today/stories/Header/index.js
  components/today/stories/Header/page-header-alt.md
  components/today/stories/Header/static/default.jpg
  components/today/stories/Header/static/study-bg-color.jpg
  components/today/stories/Header/static/study-bg-subject.png
  components/today/stories/Header/static/study-bg.jpg
  components/today/stories/index.js
  targets/lib/index.js
  targets/vue/index.js
Labels: accessibility, pr-minor

#1627 feat(component): card article / large / list
  components/buttons/index.css
  components/cards/CardArticle.vue
  components/cards/CardArticleLarge.vue
  components/cards/CardArticleList.vue
  components/cards/__tests__/CardArticle.test.js
  components/cards/__tests__/CardArticleLarge.test.js
  components/cards/__tests__/CardArticleList.test.js
  components/cards/__tests__/__snapshots__/CardArticle.test.js.snap
  components/cards/__tests__/__snapshots__/CardArticleLarge.test.js.snap
  components/cards/__tests__/__snapshots__/CardArticleList.test.js.snap
  components/cards/_card-article-large.css
  components/cards/_card-article.css
  components/cards/index.css
  components/embed/stories/VideoLandscape.vue
  components/today/stories/Cards/CardArticle.vue
  components/today/stories/Cards/CardArticleLarge.md
  components/today/stories/Cards/CardArticleLarge.vue
  components/today/stories/Cards/CardArticleList.md
  components/today/stories/Cards/CardArticleList.vue
  components/today/stories/Cards/index.js
  components/today/stories/Section/FeaturedArticles.vue
  components/today/stories/Section/SectionAlt.md
  components/today/stories/Section/StandardWithImage.vue
  components/today/stories/Section/index.js
  components/today/stories/index.js
  targets/lib/index.js
  targets/vue/index.js
Labels: homepage, pr-minor

#1628 feat(component): Card flat and card flat list
  components/cards/CardFlat.vue
  components/cards/CardFlatList.vue
  components/cards/__tests__/CardFlat.test.js
  components/cards/__tests__/CardFlatList.test.js
  components/cards/__tests__/__snapshots__/CardFlat.test.js.snap
  components/cards/__tests__/__snapshots__/CardFlatList.test.js.snap
  components/cards/_card-flat-list.css
  components/cards/_card-flat.css
  components/cards/index.css
  components/today/stories/Cards/CardFlat.md
  components/today/stories/Cards/CardFlat.vue
  components/today/stories/Cards/CardFlatList.md
  components/today/stories/Cards/CardFlatList.vue
  components/today/stories/Cards/index.js
  targets/lib/index.js
  targets/vue/index.js
Labels: homepage, pr-minor

#1630 feat(component): mega menu alt
  components/index.js
  components/megamenu/MegaMenuAlt.vue
  components/megamenu/MegaMenuAltMobile.vue
  components/megamenu/__tests__/MegaMenuAlt.test.js
  components/megamenu/__tests__/MegaMenuAltMobile.test.js
  components/megamenu/__tests__/__snapshots__/MegaMenuAlt.test.js.snap
  components/megamenu/__tests__/__snapshots__/MegaMenuAltMobile.test.js.snap
  components/megamenu/_mega-menu-alt-mobile.css
  components/megamenu/_mega-menu-alt.css
  components/megamenu/index.css
  components/megamenu/stories/MegaMenuAlt.vue
  components/megamenu/stories/index.js
  components/megamenu/stories/mega-menu-alt.md
  components/screen-reader-jump-to/ScreenReaderJumpTo.vue
  components/screen-reader-jump-to/stories/Default.vue
  package.json
  targets/lib/index.js
  targets/vue/index.js
  yarn.lock
Labels: homepage, pr-minor

#1633 feat(component): page header home
  components/header/PageHeaderHome.vue
  components/header/__tests__/PageHeaderHome.test.js
  components/header/__tests__/__snapshots__/PageHeaderHome.test.js.snap
  components/header/_page-header-home.css
  components/header/index.css
  components/today/PathfinderToday/PathfinderToday.vue
  components/today/PathfinderToday/index.css
  components/today/PathfinderToday/stories/PathfinderToday.md
  components/today/PathfinderToday/stories/Story1.vue
  components/today/PathfinderToday/stories/Story2.vue
  components/today/PathfinderToday/stories/Story3.vue
  components/today/stories/Header/PageHeaderHome.vue
  components/today/stories/Header/index.js
  components/today/stories/Header/page-header-home.md
  components/today/stories/Header/static/hero-bg.jpg
  components/today/stories/Header/static/hero-feature.png
Labels: accessibility, homepage, pr-minor

#1635 Add exports for header components
  targets/lib/index.js
  targets/vue/index.js
Labels: pr-patch

#1634 fix(component): mega menu chevron icon
  components/megamenu/MegaMenu.vue
Labels: accessibility, bug, pr-patch

#1643 chore(component): video landscape in a section
  components/embed/_video.css
  components/section/_section-alt.css
  components/today/stories/Section/SectionWithVideo.vue
  components/today/stories/Section/index.js
Labels: pr-patch

#1644 chore(css): update padding section image
  components/section/_section-image.css
Labels: pr-patch
